### ISSUE TITLE
Kanban Review

### ISSUE THREAD

**Issue by mmatongo** [medaminedev66/lunar-hotel-backend#14]
Hello, in this group we have only four members;
@julie-ify and @mmatongo  @DammyShittu  @medaminedev66 

Link to project Kanban board: https://github.com/medaminedev66/lunar-hotel-backend/projects/1

![Screenshot 2022-01-12 at 8 02 39 PM](https://user-images.githubusercontent.com/40806126/149196552-b97af233-a0ad-4e9c-9c7a-9e1d84296693.png)

**Comment by MuriloRoque** [comment]
Hi @mmatongo, @DammyShittu, @medaminedev66, @julie-ify, 

Good job so far!
There are some issues that you still need to work on to move forward but you are almost there!

## Suggested changes

- [ ] Please add a screenshot of your kanban board to this Issue description.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issues for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @mmatongo, @DammyShittu, @medaminedev66, @julie-ify, 

In my opinion, your project is complete! There is nothing else to say other than... it's time to start it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by mmatongo** [comment]
Thank you.

> Hi @mmatongo, @DammyShittu, @medaminedev66, @julie-ify,
> 
> In my opinion, your project is complete! There is nothing else to say other than... it's time to start it :shipit:
> 
> Good luck! 🎉
> 
> Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
